# Тема 10. Декораторы и исключения.
### Отчет по Теме #10 выполнила:
- Кныш Анна Анатольевна
- ПИЭ-22-1

| Задание | Лаб. раб. | Сам. раб. |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа 
## Задание №1
Наверняка вы думаете, что декораторы – это какая-то бесполезная
вещь, которая вам никогда не пригодится, но тут вдруг на паре по
математике преподаватель просит всех посчитать число Фибоначчи для
100. Кто-то будет считать вручную (так точно не нужно), кто-то
посчитает на калькуляторе, а кто-то подумает, что он самый крутой и
напишет рекурсивную программу на Python и немного огорчится,
потому что данная программа будет достаточно долго считаться, если
ее просто так запускать. Но именно тут к вам на помощь приходят
декораторы, например @lru_cache (он предназначен для решения задач
динамическим программированием, если простыми словами, то этот
декоратор запоминает промежуточные результаты и при рекурсивном
вызове функции программа не будет считать одни и те же значения, а
просто “возьмёт их из этого декоратора”). Вам нужно написать
программу, которая будет считать числа Фибоначчи для 100 и
запустить ее без этого декоратора и с ним, посмотреть на разницу во
времени решения поставленной задачи.
P.S. при запуске без декоратора можете долго не ждать, для
наглядности хватит 10 секунд ожидания

#### Выполнение:
```python
from functools import lru_cache

@lru_cache(None)
def fibonache(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    return fibonache(n-1)+fibonache(n-2)

if __name__=='__main__':
    print(fibonache(100))
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.1.png)

#### Вывод: В ходе выполнения задания мы изучили применение декораторов в Python, в частности, декоратора @lru_cache, который позволяет оптимизировать рекурсивные функции, такие как вычисление чисел Фибоначчи. Мы сравнили время выполнения программы с использованием декоратора и без него. Результаты показали, что использование @lru_cache значительно ускоряет выполнение программы, особенно при больших значениях, таких как 100. Это подчеркивает важность декораторов в оптимизации кода и повышении его эффективности, особенно в задачах, связанных с динамическим программированием.

## Задание 2
Илья пишет свой сайт и ему необходимо сделать минимальную
проверку ввода данных пользователя при регистрации. Для этого он
реализовал функцию, которая выводит данные пользователя на экран и
решил, что будет проверять правильность введённых данных при
помощи декоратора, но в этом ему потребовалась ваша помощь.
Напишите декоратор для функции, который будет принимать все
параметры вызываемой функции (имя, возраст) и проверять чтобы
возраст был больше 0 и меньше 130.
Причем заметьте, что неважно сколько пользователь введет данных на
сайт к Илье, будут обрабатываться только первые 2 аргумента
#### Выполнение:
```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age<0 or age >130:
            age='Недопустимый возраст'
        input_func(name, age)

    return output_func

@check
def personal_info(name, age):
    print(f"Name {name} Age: {age}")


if __name__ =="__main__":
    personal_info('Владимип', 38)
    personal_info('Александр', -5)
    personal_info('Петр', 138,15,48,2)
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.2.png)

#### Вывод: Мы разработали декоратор для проверки корректности ввода данных пользователя. Декоратор проверяет, чтобы возраст пользователя находился в допустимых пределах (больше 0 и меньше 130). Это позволяет избежать ошибок и некорректных данных при регистрации на сайте. Мы также увидели, что декораторы могут быть полезны для обработки и валидации входных данных, что делает код более чистым и модульным.

## Задание 3
Вам понравилась идея Ильи с сайтом, и вы решили дальше работать
вместе с ним. Но вот в вашем проекте появилась проблема, кто-то
пытается сломать вашу функцию с получением данных для сайта. Эта
функция работает только с данными integer, а какой-то недохакер
пытается все сломать и вместо нужного типа данных отправляет string.
Воспользуйтесь исключениями, чтобы неподходящий тип данных не
ломал ваш сайт.
Также дополнительно можете обернуть весь код функции в
try/except/finally для того, чтобы программа вас оповестила о том, что
выявлена какая-то ошибка или программа успешно выполнена.
#### Выполнение:
```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result=(args[0][i]*15)//10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
                print('Вся инфа обработана')

if __name__=='__main__':
    data([1,15,'Hello','gd','doof','fasdc',23,52])
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.3.png)

#### Вывод: Мы столкнулись с проблемой обработки некорректных типов данных, которые могут быть переданы в функцию. Мы использовали исключения для предотвращения сбоев программы при получении данных, что позволяет обеспечить стабильность работы сайта. Обернув код в блоки try/except/finally, мы добавили возможность информирования о возникших ошибках или успешном завершении выполнения программы. Это улучшает пользовательский опыт и делает код более надежным.

## Задание 4
Продолжая работу над сайтом, вы решили написать собственное
исключение, которое будет вызываться в случае, если в функцию
проверки имени при регистрации передана строка длиннее десяти
символов, а если имя имеет допустимую длину, то в консоль
выводиться “Успешная регистрация”

#### Выполнение:
```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name)>10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешеая регистрация')

if __name__ == '__main__':
    name='123456788889203'
    check_name(name)
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.4.png)

#### Вывод: В ходе выполнения задания мы разработали собственное исключение для проверки длины имени при регистрации на сайте. Исключение NegativeValueException вызывается, если длина имени превышает десять символов. Это позволяет нам контролировать вводимые данные и предотвращать ошибки, связанные с некорректными значениями. Если имя соответствует требованиям, выводится сообщение об успешной регистрации. Данный подход демонстрирует важность обработки исключений в программировании, что позволяет улучшить пользовательский опыт и повысить надежность приложения.

## Задание 5
После запуска сайта вы поняли, что вам необходимо добавить логгер,
для отслеживания его работы. Готовыми вариантами вы не захотели
пользоваться, и поэтому решили создать очень простую пародию. Для
этого создали две функции: __init__() (вызывается при создании класса
декоратора в программе) и __call__() (вызывается при вызове
декоратора). Создайте необходимый вам декоратор. Выведите все логи
в консоль

#### Выполнение:
```python
class SiteChecker:
    def __init__(self,func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> ПРоверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')


@SiteChecker
def site():
    print('Усердная работа сайта')

if __name__ == '__main__':
    print('> Сайт запущен')
    site()
    print('> Сайт выключен')
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.5.png)

#### Вывод:  Мы создали простой логгер для отслеживания работы сайта, реализовав класс-декоратор SiteChecker. В этом классе мы определили методы __init__() и __call__(), которые позволяют выполнять дополнительные действия при создании и вызове декоратора. Логирование в консоль помогает отслеживать состояние сайта, что является важным аспектом при разработке и поддержке веб-приложений. Этот подход демонстрирует, как можно использовать декораторы для добавления функциональности к существующим функциям, улучшая структуру и читаемость кода.

## Самостоятельная работа 
## Задание №1
Вовочка решил заняться спортивным программированием на python, но
для этого он должен знать за какое время выполняется его программа.
Он решил, что для этого ему идеально подойдет декоратор для
функции, который будет выяснять за какое время выполняется та или
иная функция. Помогите Вовочке в его начинаниях и напишите такой
декоратор.
Подсказка: необходимо использовать модуль time
Декоратор необходимо использовать для этой функции
#### Выполнение:
```python
import time

def timing_decorator(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Время выполнения функции {func.__name__}: {execution_time} секунд")
        return result
    return wrapper

@timing_decorator
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.6.png)

### Вывод:  декоратор timing_decorator принимает функцию func и возвращает новую функцию wrapper, которая измеряет время выполнения func. Декоратор затем применяется к функции fibonacci с помощью символа @. Когда fibonacci() вызывается, декоратор автоматически измеряет время выполнения этой функции и выводит результат.

## Задание №2
Посмотрев на Вовочку, вы также загорелись идеей спортивного
программирования, начав тренировки вы узнали, что для решения
некоторых задач необходимо считывать данные из файлов. Но через
некоторое время вы столкнулись с проблемой что файлы бывают
пустыми, и вы не получаете вводные данные для решения задачи.
После этого вы решили не просто считывать данные из файла, а всю
конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то
информация. Напишите код программы. Если файл пустой, то, нужно
вызвать исключение (“бросить исключение”) и вывести в консоль
“файл пустой”, а если он не пустой, то вывести информацию из файла.

#### Выполнение:
```python
def read_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            if not content:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:")
                print(content)
    except FileNotFoundError:
        print(f"Файл 'file_path' не найден")
    except Exception as e:
        print(f"Исключение: e")

if __name__ == '__main__':  
    print("Для пустого файла:")
    read_file('input.txt')  

    print("" + "=" * 30 + "")

    print("Для файла с информацией:")
    read_file('input.txt')  
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.7.png)

### Вывод: Этот код определяет функцию read_file, которая сначала пытается открыть файл, читает его содержимое и проверяет, не является ли файл пустым. Если файл пустой, генерируется исключение с сообщением "Файл пустой". Если файл не пустой, выводится содержимое файла. Если файл не найден, обрабатывается исключение FileNotFoundError.

## Задание №3
Напишите функцию, которая будет складывать 2 и введенное
пользователем число, но если пользователь введет строку или другой
неподходящий тип данных, то в консоль выведется ошибка
“Неподходящий тип данных. Ожидалось число.”. Реализовать
функционал программы необходимо через try/except и подобрать
правильный тип исключения. Создавать собственное исключение
нельзя. Проведите несколько тестов, в которых исключение вызывается
и нет. Результатом выполнения задачи будет листинг кода и
получившийся вывод в консоль

#### Выполнение:
```python
def add_two_and_number():
    try:
        user_input = input("Введите число: ")
        result = 2 + float(user_input)
        print(f"Результат сложения: {result}")
    except ValueError:
        print("Неподходящий тип данных. Ожидалось число.")


if __name__ == '__main__':
    # Тест 1: ввод корректного числа
    add_two_and_number()
    # Тест 2: ввод строки вместо числа
    add_two_and_number()
    # Тест 3: ввод другого неподходящего типа данных
    add_two_and_number()
    # Тест 4: ввод отрицательного числа
    add_two_and_number()
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.8.png)

### Вывод:используется исключение ValueError, которое возникает, если происходит ошибка преобразования строки в число с помощью float(). Если пользователь вводит корректное число, программа выполняется успешно. Если пользователь вводит строку или другой неподходящий тип данных, перехватывается исключение, и выводится соответствующее сообщение об ошибке.

## Задание №4
Создайте собственный декоратор, который будет использоваться для
двух любых вами придуманных функций. Декораторы, которые
использовались ранее в работе нельзя воссоздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода.

#### Выполнение:
```python
 import time

# Определяем класс декоратора времени выполнения
class TimingDecorator:
    def __init__(self, func):
        self.func = func

    def __call__(self, *args, **kwargs):
        start_time = time.time()  # Записываем время начала
        result = self.func(*args, **kwargs)  # Вызываем оригинальную функцию
        end_time = time.time()  # Записываем время окончания
        execution_time = end_time - start_time  # Подсчитываем время выполнения
        print(f"Время выполнения функции '{self.func.__name__}': {execution_time} секунд")  # Выводим время выполнения
        return result  # Возвращаем результат оригинальной функции

# Используем TimingDecorator для функции факториала
@TimingDecorator
def factorial(n):
    result = 1
    for i in range(1, n + 1):
        result *= i
    return result

# Используем TimingDecorator для функции генерации квадратов
@TimingDecorator
def generate_squares(n):
    return [i ** 2 for i in range(1, n + 1)]

# Основной блок выполнения
if __name__ == '__main__':
    print(factorial(5))  # Вычисляем и печатаем факториал числа 5
    print(generate_squares(5))  # Генерируем и печатаем квадраты чисел от 1 до 5
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.9.png)

### Вывод: Класс TimingDecorator: Этот класс предназначен для измерения времени выполнения любой функции, которую он декорирует. При инициализации он принимает функцию в качестве аргумента и сохраняет её.Метод call: Этот специальный метод позволяет экземпляру класса вызываться как функция. Он записывает время начала, вызывает оригинальную функцию, записывает время окончания и вычисляет время выполнения. В конце он выводит время выполнения и возвращает результат функции.Функция факториала: Эта функция вычисляет факториал заданного числа n. Она перемножает все целые числа от 1 до n и возвращает результат. Функция генерации квадратов: Эта функция создает список квадратов чисел от 1 до n, используя списковое включение (list comprehension). Таким образом, мы создали декоратор TimingDecorator, который может быть применен к различным функциям для измерения времени их выполнения.

## Задание №5
Создайте собственный декоратор, который будет использоваться для
двух любых вами придуманных функций. Декораторы, которые
использовались ранее в работе нельзя воссоздавать. Результатом
выполнения задачи будет: класс декоратора, две как-то связанными с
ним функциями, скриншот консоли с выполненной программой и
подробные комментарии, которые будут описывать работу вашего
кода.

#### Выполнение:
```python
# Определение собственного исключения CustomError, наследующего от базового класса Exception
class CustomError(Exception):
    # Инициализация исключения с возможностью передать сообщение об ошибке
    def __init__(self, message="Произошла ошибка"):
        self.message = message
        super().__init__(self.message)  # Вызов конструктора базового класса

# Функция для обработки данных пользователя
def process_user_data(name, age):
    try:
        # Проверка на наличие имени и возраста
        if not name or not age:
            raise CustomError("Имя и возраст должны быть заполнены")

        # Проверка на корректность возраста
        if not isinstance(age, int) or age < 0:
            raise CustomError("Некорректный формат возраста")

        # Если все проверки пройдены, вывод данных пользователя
        print(f"Данные пользователя: Имя - name, Возраст - age лет")
    except CustomError as e:
        # Обработка пользовательского исключения
        print(f"Ошибка при обработке данных пользователя: e")

# Функция для чтения содержимого файла
def read_file_content(file_path):
    try:
        # Попытка открыть файл для чтения
        with open(file_path, 'r') as file:
            content = file.read()  # Чтение содержимого файла
            # Проверка на наличие содержимого в файле
            if not content:
                raise CustomError("Файл пустой")
            else:
                print(f"Содержимое файла: content")  # Вывод содержимого файла
    except FileNotFoundError:
        # Обработка исключения при отсутствии файла
        print(f"Ошибка: Файл 'file_path' не найден.")
    except CustomError as e:
        # Обработка пользовательского исключения
        print(f"Ошибка при чтении файла: e")

# Главный блок программы
if __name__ == '__main__':  # Исправлено: корректное условие проверки запуска скрипта
    # Тест 1: Правильные данные пользователя
    process_user_data("John Doe", 30)

    # Тест 2: Некорректный возраст (вызовет исключение)
    process_user_data("Alice", -25)

    # Тест 3: Пустое имя пользователя (вызовет исключение)
    process_user_data("", 22)

    # Тест 4: Чтение содержимого файла
    read_file_content("input.txt")

    # Тест 5: Чтение из пустого файла (вызовет исключение) - этот тест не удастся, если файл не существует
    read_file_content("input.txt") 
```
#### Результат:
![Меню](https://github.com/Knysha04/SoftwareEngineering/blob/main/pic/Tema10.10.png)

### Вывод: Класс CustomError представляет собой пользовательское исключение, которое позволяет создавать более информативные сообщения об ошибках, специфичные для конкретного приложения, при этом конструктор принимает сообщение, обрабатываемое базовым классом Exception. Функция processuserdata отвечает за обработку вводимых данных пользователя и проверяет их корректность, включая наличие имени и возраста, а также проверку возраста на соответствие требованиям (должен быть целым положительным числом); в случае обнаружения ошибок выбрасывается исключение CustomError, которое затем обрабатывается в блоке except. Функция readfilecontent предназначена для чтения содержимого указанного файла: она открывает файл для чтения, выводит его содержимое и проверяет, пустой ли файл, выдавая в этом случае CustomError, а также обрабатывает ошибки, связанные с отсутствием файла (FileNotFoundError) и пользовательские ошибки (CustomError). В главном блоке программы выполняются тестовые данные для функций, где первый тест проходит успешно, второй и третий тесты вызывают исключения, демонстрируя работу обработки ошибок, четвертый тест пытается считать содержимое файла, а пятый тест ищет пустой файл, что также приводит к возникновению ошибки.

## Общий вывод: В Python декораторы и исключения являются важными элементами языка, предоставляющими эффективные и гибкие механизмы для организации кода и обработки ошибок.
